#!/bin/sh

echo Indenting main.c
indent -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 -d0 -di1 -nfc1 -i3 -ip0 -l120 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts3 -il1 --verbose --no-tabs -l120 main.c

echo Compiling main.c
if gcc -Wall -O2 main.c -lcsfml-graphics -lcsfml-window -lcsfml-audio -o kcm; then
echo Success
echo Starting app..
./kcm
else
echo Oops
fi
echo Cleaning up temp files
rm *.c~
echo Done
